Repository ajou-capstone/campus-market-spring, pull requests merged in 2024-12, with the labels that each got.

#146 feat: 관리자 기능 추가
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
Labels: feature

#147 feat: 로그아웃 기능 추가
  build.gradle
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/controller/AuthController.java
  src/main/java/LinkerBell/campus_market_spring/global/jwt/JwtFilter.java
  src/main/java/LinkerBell/campus_market_spring/global/jwt/JwtUtils.java
  src/main/java/LinkerBell/campus_market_spring/global/redis/RedisConfig.java
  src/main/java/LinkerBell/campus_market_spring/global/redis/RedisService.java
  src/main/java/LinkerBell/campus_market_spring/service/AuthService.java
  src/test/java/LinkerBell/campus_market_spring/global/redis/RedisTest.java
  src/test/java/LinkerBell/campus_market_spring/service/AuthServiceTest.java
Labels: feature

#150 feat : 채팅 알림 기능 추가
  src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
  src/main/java/LinkerBell/campus_market_spring/service/ChatPropertiesService.java
  src/main/java/LinkerBell/campus_market_spring/service/ChattingService.java
  src/main/java/LinkerBell/campus_market_spring/service/FcmService.java
Labels: feature

#153 feat: 관리자용 사용자 프로필 정보 가져오기 기능 추가
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/dto/OtherProfileResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/service/ProfileService.java
Labels: feature

#159 fix : 채팅 알림 보낼 때 userId를 판매자와 구매자일 때 다르게 저장하게 수정
  src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
  src/main/java/LinkerBell/campus_market_spring/service/ChattingService.java
Labels: fix

#160 fix : 채팅방 정보에 thumbnail 추가
  src/main/java/LinkerBell/campus_market_spring/dto/ChatRoomDataResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/service/ChatRoomService.java
Labels: fix

#161 fix : 채팅 알림 보낼 때 title을 상대 닉네임으로 수정
  src/main/java/LinkerBell/campus_market_spring/service/ChattingService.java
Labels: fix

#162 fix : 채팅방 만들 때 thumbnail 정보 추가
  src/main/java/LinkerBell/campus_market_spring/dto/ChatRoomResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/service/ChatRoomService.java
Labels: fix

#163 fix : 거래 내역 불러올 때 response에 작성일자, 수정일자, 리뷰 작성했는지 여부 추가
  src/main/java/LinkerBell/campus_market_spring/dto/DealHistoryResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/repository/ReviewRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/DealHistoryService.java
Labels: fix

#165 fix : 거래 내역 정보에 작성자 닉네임 추가
  src/main/java/LinkerBell/campus_market_spring/dto/DealHistoryResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/service/DealHistoryService.java
Labels: fix

#166 feat : 나에게 작성된 리뷰를 가져오는 기능 추가
  src/main/java/LinkerBell/campus_market_spring/controller/ReviewController.java
  src/main/java/LinkerBell/campus_market_spring/repository/ReviewRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/ReviewService.java
  src/test/java/LinkerBell/campus_market_spring/controller/ReviewControllerTest.java
Labels: feature

#167 feat: 문의, 신고 목록을 볼 때 처리 여부에 따라 필터링하는 기능 추가
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminQaSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/repository/ItemReportRepository.java
  src/main/java/LinkerBell/campus_market_spring/repository/QaRepository.java
  src/main/java/LinkerBell/campus_market_spring/repository/UserReportRepository.java
  src/test/java/LinkerBell/campus_market_spring/admin/controller/AdminControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/admin/service/AdminServiceTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/ItemReportRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/QaRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/UserReportRepositoryTest.java
Labels: feature

#168 fix : 유저 평점 계산 과정에서 리뷰 수 세는 방식 수정 및 로그 추가
  src/main/java/LinkerBell/campus_market_spring/repository/ReviewRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/ReviewService.java
Labels: fix

#170 feat: 관리자용 사용자 정보 가져오기 기능 추가
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/dto/UserInfoDto.java
  src/main/java/LinkerBell/campus_market_spring/repository/UserRepository.java
  src/test/java/LinkerBell/campus_market_spring/global/redis/RedisTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/UserRepositoryTest.java
Labels: feature

#171 fix: 관리자용 사용자 프로필 내용 수정
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/repository/UserRepository.java
  src/test/java/LinkerBell/campus_market_spring/repository/UserRepositoryTest.java
Labels: feature

#172 fix : 유저 평점 계산 과정 수정
  src/main/java/LinkerBell/campus_market_spring/service/ReviewService.java
  src/test/java/LinkerBell/campus_market_spring/service/ReviewServiceTest.java
Labels: fix

#173 fix: 관리자용 사용자 리스트 보기 수정
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/dto/UserInfoDto.java
  src/main/java/LinkerBell/campus_market_spring/repository/UserRepository.java
  src/test/java/LinkerBell/campus_market_spring/repository/UserRepositoryTest.java
Labels: fix

#174 fix : ReviewService에 로그 추가
  src/main/java/LinkerBell/campus_market_spring/service/ReviewService.java
Labels: hotfix

#175 fix : 채팅 알림 보내는 코드 수정
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/service/ChattingService.java
Labels: hotfix

#176 fix : 거래 내역 정보에 구매자 id 추가
  src/main/java/LinkerBell/campus_market_spring/dto/DealHistoryResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/service/DealHistoryService.java
Labels: hotfix

#177 feat: admin item 검색에 itemStatus 필터 추가
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/global/error/GlobalExceptionHandler.java
  src/main/java/LinkerBell/campus_market_spring/repository/ItemRepositoryCustom.java
  src/main/java/LinkerBell/campus_market_spring/repository/ItemRepositoryImpl.java
  src/test/java/LinkerBell/campus_market_spring/admin/controller/AdminControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/ItemRepositoryTest.java
Labels: feature

#178 fix : getChatRoom 로그 추가
  src/main/java/LinkerBell/campus_market_spring/service/ChatRoomService.java
Labels: hotfix

#181 fix: image가 itemThumbnail로 가면 s3 지워지는 오류 수정
  src/main/java/LinkerBell/campus_market_spring/service/ItemService.java
Labels: hotfix

#179 fix: validation 체크 추가, 회원 탈퇴 기능 추가
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/controller/AuthController.java
  src/main/java/LinkerBell/campus_market_spring/controller/ProfileController.java
  src/main/java/LinkerBell/campus_market_spring/dto/CampusRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/MailRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/ProfileRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/VerificationCodeRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/global/auth/LoginArgumentResolver.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/global/error/GlobalExceptionHandler.java
  src/main/java/LinkerBell/campus_market_spring/repository/BlacklistRepository.java
  src/main/java/LinkerBell/campus_market_spring/repository/UserFcmTokenRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/AuthService.java
  src/main/java/LinkerBell/campus_market_spring/service/FcmService.java
  src/test/java/LinkerBell/campus_market_spring/admin/service/AdminServiceTest.java
  src/test/java/LinkerBell/campus_market_spring/controller/ProfileControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/BlacklistRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/service/AuthServiceTest.java
Labels: feature, fix

#180 fix: 관리자용 문의 및 사용자 신고 상세 내용 정보 수정 외 1가지
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminItemReportRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminItemSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminLoginRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminQaRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminQaResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminQaSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminUserReportRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/ItemReportResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/ItemReportSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/UserReportResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/UserReportSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/controller/QaController.java
  src/main/java/LinkerBell/campus_market_spring/domain/UserReport.java
  src/main/java/LinkerBell/campus_market_spring/dto/ItemReportCategoryResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/QaCategoryResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/QaRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/QaResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/QaSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/UserReportCategoryResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/global/config/FirebaseConfig.java
  src/test/java/LinkerBell/campus_market_spring/admin/service/AdminServiceTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/ItemRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/service/QaServiceTest.java
Labels: fix

#182 fix: 탈퇴한 사용자인지 확인하는 기능 추가
  src/main/java/LinkerBell/campus_market_spring/global/auth/LoginArgumentResolver.java
  src/main/java/LinkerBell/campus_market_spring/service/AuthService.java
Labels: fix

#183 fix: 사용자 신고 처리 수정
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
Labels: fix

#184 fix: 로그인 토큰 validation 추가
  src/main/java/LinkerBell/campus_market_spring/controller/AuthController.java
  src/main/java/LinkerBell/campus_market_spring/dto/AuthRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/global/error/GlobalExceptionHandler.java
Labels: fix

#185 style: 디버깅 로그 코드 삭제
  src/main/java/LinkerBell/campus_market_spring/controller/ChatMessageController.java
  src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
  src/main/java/LinkerBell/campus_market_spring/global/config/HttpHandshakeInterceptor.java
  src/main/java/LinkerBell/campus_market_spring/global/config/SchedulerConfig.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketConfig.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketEventListener.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketHandler.java
  src/main/java/LinkerBell/campus_market_spring/global/jwt/JwtUtils.java
  src/main/java/LinkerBell/campus_market_spring/service/ChatMessageService.java
  src/main/java/LinkerBell/campus_market_spring/service/ChatPropertiesService.java
  src/main/java/LinkerBell/campus_market_spring/service/ChatRoomService.java
  src/main/java/LinkerBell/campus_market_spring/service/ChattingService.java
  src/main/java/LinkerBell/campus_market_spring/service/FcmNotificationService.java
  src/main/java/LinkerBell/campus_market_spring/service/FcmService.java
  src/main/java/LinkerBell/campus_market_spring/service/GoogleAuthService.java
  src/main/java/LinkerBell/campus_market_spring/service/ItemService.java
  src/main/java/LinkerBell/campus_market_spring/service/ReviewService.java
  src/test/java/LinkerBell/campus_market_spring/global/jwt/JwtUtilsTest.java
Labels: style
