Repository ajou-capstone/campus-market-spring, pull requests merged in 2024-11, with the labels that each got.

#32 feat: 약관 기능 추가
  src/main/java/LinkerBell/campus_market_spring/controller/TermsController.java
  src/main/java/LinkerBell/campus_market_spring/domain/UserAndTerms.java
  src/main/java/LinkerBell/campus_market_spring/dto/CollectionResponse/TermsCollectionRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/TermsRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/repository/TermsRepository.java
  src/main/java/LinkerBell/campus_market_spring/repository/UserAndTermsRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/TermsService.java
  src/test/java/LinkerBell/campus_market_spring/controller/TermsControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/UserAndTermsRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/service/TermsServiceTest.java
Labels: feature

#37 fix: 약관 동의 버그 수정
  src/main/java/LinkerBell/campus_market_spring/service/TermsService.java
Labels: fix

#39 fix: 약관 동의 기능 버그 수정
  src/main/java/LinkerBell/campus_market_spring/dto/TermsRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/service/TermsService.java
  src/test/java/LinkerBell/campus_market_spring/controller/TermsControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/service/TermsServiceTest.java
Labels: fix

#40 feat: s3 설정, presigned URL 기능 추가
  src/main/generated/LinkerBell/campus_market_spring/dto/QItemSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/CampusMarketSpringApplication.java
  src/main/java/LinkerBell/campus_market_spring/controller/S3Controller.java
  src/main/java/LinkerBell/campus_market_spring/dto/S3ResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/global/config/AwsConfig.java
  src/main/java/LinkerBell/campus_market_spring/global/config/AwsProperties.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/global/error/GlobalExceptionHandler.java
  src/main/java/LinkerBell/campus_market_spring/service/S3Service.java
  src/test/java/LinkerBell/campus_market_spring/controller/S3ControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/service/S3ServiceTest.java
Labels: feature, fix

#43 feat: item 거래 상태 변경 기능 구현 및 테스트
  src/main/java/LinkerBell/campus_market_spring/controller/ItemController.java
  src/main/java/LinkerBell/campus_market_spring/domain/BaseEntity.java
  src/main/java/LinkerBell/campus_market_spring/dto/ItemStatusChangeRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/global/error/GlobalExceptionHandler.java
  src/main/java/LinkerBell/campus_market_spring/repository/ChatRoomRepository.java
  src/main/java/LinkerBell/campus_market_spring/repository/ItemRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/ItemService.java
  src/test/java/LinkerBell/campus_market_spring/controller/ItemControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/ItemRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/service/ItemServiceTest.java
Labels: feature

#42 feat: 다른 사용자 프로필 정보 확인하기 기능 추가
  src/main/java/LinkerBell/campus_market_spring/controller/AuthController.java
  src/main/java/LinkerBell/campus_market_spring/controller/ProfileController.java
  src/main/java/LinkerBell/campus_market_spring/dto/OtherProfileResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/service/ProfileService.java
  src/test/java/LinkerBell/campus_market_spring/controller/ProfileControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/service/ProfileServiceTest.java
Labels: feature

#45 fix: itemRegister의 imageUrl이 잘리는 버그 수정
  src/main/java/LinkerBell/campus_market_spring/dto/ItemRegisterRequestDto.java
Labels: fix

#44 feat: fcm token 등록 기능 추가
  src/main/java/LinkerBell/campus_market_spring/controller/AuthController.java
  src/main/java/LinkerBell/campus_market_spring/domain/UserFcmToken.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/repository/UserFcmTokenRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/AuthService.java
  src/test/java/LinkerBell/campus_market_spring/controller/AuthControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/UserFcmTokenRepositoryTest.java
Labels: feature

#46 fix: s3 url 버그 수정
  src/main/java/LinkerBell/campus_market_spring/service/S3Service.java
Labels: fix

#51 feat: fcm 설정 및 키워드 알림 기능 구현 및 테스트
  .github/workflows/spring-ci.yml
  .gitignore
  src/main/java/LinkerBell/campus_market_spring/domain/Category.java
  src/main/java/LinkerBell/campus_market_spring/domain/Keyword.java
  src/main/java/LinkerBell/campus_market_spring/dto/FcmMessageDto.java
  src/main/java/LinkerBell/campus_market_spring/global/config/FirebaseConfig.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/repository/KeywordRepository.java
  src/main/java/LinkerBell/campus_market_spring/repository/UserFcmTokenRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/FcmService.java
  src/main/java/LinkerBell/campus_market_spring/service/ItemService.java
  src/main/java/LinkerBell/campus_market_spring/service/KeywordService.java
  src/test/java/LinkerBell/campus_market_spring/controller/ItemControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/ItemRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/KeywordRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/UserFcmTokenRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/service/FcmServiceTest.java
  src/test/java/LinkerBell/campus_market_spring/service/ItemServiceTest.java
  src/test/java/LinkerBell/campus_market_spring/service/KeywordServiceTest.java
Labels: feature, fix

#48 feat: 좋아요 누르기 기능 추가
  src/main/java/LinkerBell/campus_market_spring/controller/LikeController.java
  src/main/java/LinkerBell/campus_market_spring/dto/LikeResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/repository/LikeRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/LikeService.java
  src/test/java/LinkerBell/campus_market_spring/controller/LikeControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/LikeRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/service/LikeServiceTest.java
Labels: feature, fix

#54 feat : null체크 기능, requestDto 추가
  src/main/java/LinkerBell/campus_market_spring/controller/ChatMessageController.java
  src/main/java/LinkerBell/campus_market_spring/dto/GetMessageContentsRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/ReadMessageRequestDto.java
Labels: feature

#59 fix: jwt 에 userId 추가
  src/main/java/LinkerBell/campus_market_spring/global/jwt/JwtUtils.java
  src/main/java/LinkerBell/campus_market_spring/service/AuthService.java
  src/test/java/LinkerBell/campus_market_spring/service/AuthServiceTest.java
Labels: fix

#61 feat : WebSocketHandler에 Connect 시에 유저 정보를 저장하는 기능 추가
  src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketConfig.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketHandler.java
Labels: feature

#62 feat : 시간표 관련 기능 추가
  src/main/java/LinkerBell/campus_market_spring/controller/TimetableController.java
  src/main/java/LinkerBell/campus_market_spring/dto/TimetableRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/TimetableResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/service/TimetableService.java
  src/test/java/LinkerBell/campus_market_spring/service/TimetableServiceTest.java
Labels: feature

#63 feat : handshakeinterceptor 추가
  src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
  src/main/java/LinkerBell/campus_market_spring/global/config/HttpHandshakeInterceptor.java
  src/main/java/LinkerBell/campus_market_spring/global/config/SecurityConfig.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketConfig.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketHandler.java
  src/main/java/LinkerBell/campus_market_spring/global/jwt/JwtFilter.java
Labels: feature

#73 feat: itemSearch에서 좋아요 눌렀는지 확인하는 기능 추가
  src/main/java/LinkerBell/campus_market_spring/dto/ItemSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/repository/ItemRepositoryCustom.java
  src/main/java/LinkerBell/campus_market_spring/repository/ItemRepositoryImpl.java
  src/main/java/LinkerBell/campus_market_spring/service/ItemService.java
  src/test/java/LinkerBell/campus_market_spring/repository/ItemRepositoryTest.java
Labels: feature

#75 fix : subscribe시에 destination log를 찍는 기능 추가
  src/main/java/LinkerBell/campus_market_spring/controller/ChatMessageController.java
  src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketHandler.java
  src/main/java/LinkerBell/campus_market_spring/service/ChatMessageService.java
Labels: fix

#76 fix : 채팅 메시지 저장 시에 contentType이 null인 경우 체크
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/service/ChattingService.java
Labels: fix

#78 feat : 여러 log들 추가
  src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
  src/main/java/LinkerBell/campus_market_spring/dto/ChattingResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketHandler.java
  src/main/java/LinkerBell/campus_market_spring/global/jwt/JwtUtils.java
Labels: feature

#79 fix : responseDto 필드명 수정
  src/main/java/LinkerBell/campus_market_spring/dto/ChattingResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/service/ChattingService.java
  src/test/java/LinkerBell/campus_market_spring/service/ChattingServiceTest.java
Labels: fix

#80 feat : unsubscribe할 때에 log를 찍음
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketHandler.java
Labels: feature

#82 feat : presend시에 messsage payload와 header를 출력
  src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketHandler.java
Labels: feature

#83 feat : postSend로 chattingResponseDto가 잘 보내졌는지 확인
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketHandler.java
Labels: feature

#84 fix : 불필요한 log info들 제거 후 post send에 log info 추가
  src/main/java/LinkerBell/campus_market_spring/global/config/HttpHandshakeInterceptor.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketHandler.java
Labels: fix

#85 feat : convertAndSend할 때 헤더 정보를 추가
  src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
Labels: feature

#86 fix : convertAndSend대신 @SendTo를 사용
  src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
Labels: fix

#87 fix : payload 어노테이션 추가
  src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
Labels: fix

#88 feat : accessor 출력 코드 추가, destinationPrefix 수정
  src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketConfig.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketHandler.java
Labels: feature

#90 feat : 로컬 test용 코드 추가
  src/main/java/LinkerBell/campus_market_spring/global/config/HttpHandshakeInterceptor.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketHandler.java
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketSecurityConfig.java
Labels: feature

#91 feat : nativeHeader에서 토큰을 읽게 변경
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketHandler.java
Labels: feature

#93 feat : WebSocketEventListener 추가
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketEventListener.java
Labels: feature

#95 feat : outbound에서 send 체크하는 기능 추가
  src/main/java/LinkerBell/campus_market_spring/global/config/WebSocketConfig.java
Labels: feature

#97 comment: jwt log 추가
  src/main/java/LinkerBell/campus_market_spring/global/jwt/JwtUtils.java
Labels: fix

#89 fix: s3 presigned url 발급 기능 수정
  src/main/generated/LinkerBell/campus_market_spring/dto/QItemSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/service/S3Service.java
  src/test/java/LinkerBell/campus_market_spring/service/S3ServiceTest.java
Labels: fix

#99 feat : 채팅 contenttype timetable인 경우 처리, validation token log 삭제
  src/main/java/LinkerBell/campus_market_spring/global/jwt/JwtUtils.java
  src/main/java/LinkerBell/campus_market_spring/service/ChattingService.java
Labels: feature

#101 feat : 같은 판매자가 같은 아이템의 거래 버튼을 눌렀을 때 채팅방을 또 만들지 않게 수정
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/repository/ChatRoomRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/ChatRoomService.java
  src/main/java/LinkerBell/campus_market_spring/service/ChattingService.java
Labels: feature

#100 fix: 같은 생성시간시, itemId가큰 순으로 보여주기
  src/main/java/LinkerBell/campus_market_spring/repository/ItemRepositoryImpl.java
Labels: fix

#102 feat: 좋아요 삭제하기 기능 추가
  src/main/java/LinkerBell/campus_market_spring/controller/LikeController.java
  src/main/java/LinkerBell/campus_market_spring/domain/User.java
  src/main/java/LinkerBell/campus_market_spring/dto/LikeDeleteResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/LikeSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/repository/LikeRepository.java
  src/main/java/LinkerBell/campus_market_spring/repository/LikeRepositoryCustom.java
  src/main/java/LinkerBell/campus_market_spring/repository/LikeRepositoryImpl.java
  src/main/java/LinkerBell/campus_market_spring/service/LikeService.java
  src/test/java/LinkerBell/campus_market_spring/controller/LikeControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/LikeRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/service/LikeServiceTest.java
Labels: feature

#106 fix: 프로필 이미지 설정 기능 수정
  src/main/java/LinkerBell/campus_market_spring/service/ProfileService.java
Labels: fix

#103 fix: 좋아요 목록 가져오기 기능 수정
  src/main/java/LinkerBell/campus_market_spring/controller/LikeController.java
  src/main/java/LinkerBell/campus_market_spring/repository/LikeRepositoryImpl.java
  src/main/java/LinkerBell/campus_market_spring/service/LikeService.java
  src/test/java/LinkerBell/campus_market_spring/controller/LikeControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/LikeRepositoryTest.java
Labels: fix

#108 fix: AuthUserDto 생성 로직 수정
  src/main/java/LinkerBell/campus_market_spring/dto/AuthUserDto.java
  src/main/java/LinkerBell/campus_market_spring/global/auth/LoginArgumentResolver.java
  src/main/java/LinkerBell/campus_market_spring/global/jwt/JwtUtils.java
  src/main/java/LinkerBell/campus_market_spring/service/AuthService.java
  src/test/java/LinkerBell/campus_market_spring/service/AuthServiceTest.java
  src/test/java/LinkerBell/campus_market_spring/service/ChatRoomServiceTest.java
Labels: fix

#109 feat: admin 로그인 기능 추가
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminLoginRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/controller/AuthController.java
  src/main/java/LinkerBell/campus_market_spring/domain/Role.java
  src/main/java/LinkerBell/campus_market_spring/global/config/SecurityConfig.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/global/jwt/JwtFilter.java
  src/main/java/LinkerBell/campus_market_spring/service/AuthService.java
  src/main/java/LinkerBell/campus_market_spring/service/FcmService.java
  src/main/java/LinkerBell/campus_market_spring/service/GoogleAuthService.java
  src/test/java/LinkerBell/campus_market_spring/admin/service/AdminServiceTest.java
  src/test/java/LinkerBell/campus_market_spring/controller/AuthControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/LikeRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/UserRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/service/AuthServiceTest.java
  src/test/java/LinkerBell/campus_market_spring/service/LikeServiceTest.java
  src/test/java/LinkerBell/campus_market_spring/service/ProfileServiceTest.java
Labels: feature

#116 feat: 관리자 api 권한 체크 에러 핸들러 추가
  src/main/java/LinkerBell/campus_market_spring/global/auth/CustomAccessDeniedHandler.java
  src/main/java/LinkerBell/campus_market_spring/global/config/SecurityConfig.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
Labels: feature

#119 feat: 관리자용 상품 검색 기능 구현
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminItemSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/repository/ItemRepositoryCustom.java
  src/main/java/LinkerBell/campus_market_spring/repository/ItemRepositoryImpl.java
  src/test/java/LinkerBell/campus_market_spring/repository/ItemRepositoryTest.java
Labels: feature

#123 fix : review 길이 제한을 200자로 조정
  src/main/java/LinkerBell/campus_market_spring/controller/ReviewController.java
  src/main/java/LinkerBell/campus_market_spring/domain/Review.java
  src/main/java/LinkerBell/campus_market_spring/dto/ReviewRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/global/error/GlobalExceptionHandler.java
  src/main/java/LinkerBell/campus_market_spring/repository/ReviewRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/ReviewService.java
  src/test/java/LinkerBell/campus_market_spring/controller/ReviewControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/ReviewRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/service/ReviewServiceTest.java
Labels: fix

#121 feat: 관리자용 상품 신고 목록 보기 기능 v1
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/ItemReportSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/dto/SliceResponse.java
  src/main/java/LinkerBell/campus_market_spring/repository/ItemReportRepository.java
  src/test/java/LinkerBell/campus_market_spring/repository/ItemReportRepositoryTest.java
Labels: feature

#124 feat: 문의 기능 추가
  src/main/java/LinkerBell/campus_market_spring/controller/QaController.java
  src/main/java/LinkerBell/campus_market_spring/domain/QA.java
  src/main/java/LinkerBell/campus_market_spring/domain/QaCategory.java
  src/main/java/LinkerBell/campus_market_spring/dto/QaCategoryResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/QaRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/global/error/GlobalExceptionHandler.java
  src/main/java/LinkerBell/campus_market_spring/repository/QaRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/QaService.java
  src/test/java/LinkerBell/campus_market_spring/controller/QaControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/QaRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/service/QaServiceTest.java
  src/test/java/LinkerBell/campus_market_spring/service/S3ServiceTest.java
Labels: feature

#125 feat: 관리자용 사용자 신고 목록 보기 기능 구현
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/UserReportSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/repository/UserReportRepository.java
  src/test/java/LinkerBell/campus_market_spring/admin/controller/AdminControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/ItemReportRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/UserReportRepositoryTest.java
Labels: feature

#127 feat: keyword 등록, 가져오기, 삭제 기능 및 테스트 코드 구현
  src/main/java/LinkerBell/campus_market_spring/controller/KeywordController.java
  src/main/java/LinkerBell/campus_market_spring/domain/Keyword.java
  src/main/java/LinkerBell/campus_market_spring/dto/CollectionResponse/KeywordCollectionResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/KeywordRegisterRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/KeywordRegisterResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/KeywordResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/global/error/GlobalExceptionHandler.java
  src/main/java/LinkerBell/campus_market_spring/repository/KeywordRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/ItemService.java
  src/main/java/LinkerBell/campus_market_spring/service/KeywordService.java
  src/test/java/LinkerBell/campus_market_spring/controller/KeywordControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/KeywordRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/service/KeywordServiceTest.java
Labels: feature

#129 feat: 상품, 사용자 신고 상세 내용 보기 기능 구현
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/ItemReportResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/UserReportResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/test/java/LinkerBell/campus_market_spring/repository/ItemReportRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/UserReportRepositoryTest.java
Labels: feature

#130 feat : 리뷰 목록 가져오기 기능 추가
  src/main/java/LinkerBell/campus_market_spring/controller/ReviewController.java
  src/main/java/LinkerBell/campus_market_spring/dto/ReviewResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/repository/ReviewRepository.java
  src/main/java/LinkerBell/campus_market_spring/repository/ReviewRepositoryCustom.java
  src/main/java/LinkerBell/campus_market_spring/repository/ReviewRepositoryImpl.java
  src/main/java/LinkerBell/campus_market_spring/service/ReviewService.java
  src/test/java/LinkerBell/campus_market_spring/controller/ReviewControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/ReviewRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/service/ReviewServiceTest.java
Labels: feature

#131 feat: 관리자용 상품 신고 처리 기능 구현
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminItemReportRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/global/error/GlobalExceptionHandler.java
  src/test/java/LinkerBell/campus_market_spring/repository/ItemReportRepositoryTest.java
Labels: feature

#132 feat: 관리자용 사용자 신고 처리 기능 구현
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminUserReportRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/domain/Blacklist.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/global/error/GlobalExceptionHandler.java
  src/main/java/LinkerBell/campus_market_spring/global/error/exception/CustomException.java
  src/main/java/LinkerBell/campus_market_spring/repository/BlacklistRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/AuthService.java
  src/test/java/LinkerBell/campus_market_spring/admin/service/AdminServiceTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/BlacklistRepositoryTest.java
Labels: feature

#134 feat: 관리자용 문의 기능 구현
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminQaRequestDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminQaResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/dto/AdminQaSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/admin/service/AdminService.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/global/error/GlobalExceptionHandler.java
  src/main/java/LinkerBell/campus_market_spring/repository/QaRepository.java
  src/test/java/LinkerBell/campus_market_spring/repository/QaRepositoryTest.java
Labels: feature

#135 feat: 사용자 문의 기능 구현
  src/main/java/LinkerBell/campus_market_spring/controller/QaController.java
  src/main/java/LinkerBell/campus_market_spring/dto/QaResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/dto/QaSearchResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/repository/QaRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/QaService.java
  src/test/java/LinkerBell/campus_market_spring/controller/QaControllerTest.java
  src/test/java/LinkerBell/campus_market_spring/repository/QaRepositoryTest.java
  src/test/java/LinkerBell/campus_market_spring/service/QaServiceTest.java
Labels: feature

#137 feat : 거래 내역을 가져오는 기능 추가
  src/main/java/LinkerBell/campus_market_spring/controller/DealHistoryController.java
  src/main/java/LinkerBell/campus_market_spring/dto/DealHistoryResponseDto.java
  src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
  src/main/java/LinkerBell/campus_market_spring/repository/ItemRepository.java
  src/main/java/LinkerBell/campus_market_spring/service/DealHistoryService.java
Labels: feature

#138 fix: adminController 수정
  src/main/java/LinkerBell/campus_market_spring/admin/controller/AdminController.java
Labels: fix

#136 feat: 스케쥴러 추가
  src/main/java/LinkerBell/campus_market_spring/CampusMarketSpringApplication.java
  src/main/java/LinkerBell/campus_market_spring/global/config/SchedulerConfig.java
Labels: feature

#140 refactor: S3Serivce, TermsService 리팩토링
  src/main/java/LinkerBell/campus_market_spring/service/S3Service.java
  src/main/java/LinkerBell/campus_market_spring/service/TermsService.java
Labels: refactor

#141 fix : loginUserId와 requestUserId를 equals로 비교하게 변경
  src/main/java/LinkerBell/campus_market_spring/service/DealHistoryService.java
Labels: fix
